### ISSUE TITLE
Support basic email display

### ISSUE THREAD

**Issue by ericholscher** [tell-k/sphinxcontrib-gravatar#2]
It would be great if we could simply use this as:

```
.. gravatar:: email@domain.com
   :width: 70%
```

or something along those lines. Having to register users in the conf.py seems a bit overboard for basic usage.

**Comment by tell-k** [comment]
@ericholscher  Thanks for your suggestion.

By the link of the "Show source" Sphinx, anyone can see that the contents of the restructuredText.
In other words, it will that would have been published the e-mail address unintentionally.
In order to protect the user's personal information, it’s good to keep it as it is.

Thx.
